try {
    console.log("workin");
    nonExistentFunction();
  } catch (err) {
    console.log(err);
  } finally {
    console.log("bylo w tym pustym catchu cheba");
  }
  